Document: reprof
Title: Debian reprof Manual
Author: <insert document author here>
Abstract: This manual describes what reprof is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/reprof/reprof.sgml.gz

Format: postscript
Files: /usr/share/doc/reprof/reprof.ps.gz

Format: text
Files: /usr/share/doc/reprof/reprof.text.gz

Format: HTML
Index: /usr/share/doc/reprof/html/index.html
Files: /usr/share/doc/reprof/html/*.html
